### ISSUE TITLE
Suggestion: Revise the code to align with the Paper

### ISSUE THREAD

**Issue by zheBytedance** [BMWTree/BMWTree#1]
Hey, you have done a great work. But I can't find the CALC module as well as RPU module in the code. I think the alignment of code and paper may make the code more readable.

**Comment by BMWTree** [comment]
> Hey, you have done a great work. But I can't find the CALC module as well as RPU module in the code. I think the alignment of code and paper may make the code more readable.

Hello, thank you for your interest of our work. The CALC and RPU module in the paper are for presentation and are not defined as a separate module. We are considering to modify the code in the future.

**Comment by zheBytedance** [comment]
Good, Thank you for clarifying.
